name: CMake CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # FOR LOCAL TESTING
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -S ./src/ -B ./src/build -DBUILD_TESTS=ON

      - name: Build
        run: cmake --build ./src/build

      - name: Test
        run: ctest --test-dir ./src/build --output-on-failure
